name = "RustyIceberg"
uuid = "390bdf5b-b624-43dc-a846-0ef7a3405804"
version = "0.5.2"

[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
iceberg_rust_ffi_jll = "6bd5c94f-693c-53e3-983d-a09fad412f22"

[compat]
Arrow = "2.0"
Preferences = "1.3"
iceberg_rust_ffi_jll = "0.6"
julia = "1.10"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DataFrames", "BenchmarkTools", "HTTP", "JSON", "Base64"]
