name: Release
on:
  release:
    types: [created]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  test-julia-1-10:
    uses: ./.github/workflows/test.yml
    with:
      build_rust: false
      julia_version: '1.10'
      os: ubuntu-latest
      arch: x64

  test-julia-1-11:
    uses: ./.github/workflows/test.yml
    with:
      build_rust: false
      julia_version: '1.11'
      os: ubuntu-latest
      arch: x64
