name: Test

on:
  workflow_call:
    inputs:
      build_rust:
        description: 'Whether to build Rust FFI library from source'
        required: true
        type: boolean
      julia_version:
        description: 'Julia version to use'
        required: true
        type: string
      os:
        description: 'Operating system to run on'
        required: true
        type: string
      arch:
        description: 'Architecture to run on'
        required: true
        type: string

jobs:
  test:
    name: Julia ${{ inputs.julia_version }} - ${{ inputs.os }} - ${{ inputs.arch }}
    env:
      JULIA_NUM_THREADS: 2
      # TODO iceberg_rust_ffi requires this and panics otherwise, we should fix that (test
      # bucket is publicly accessible).
      AWS_ACCESS_KEY_ID: root
      AWS_SECRET_ACCESS_KEY: password
      AWS_ENDPOINT_URL: http://localhost:9000
      AWS_REGION: us-east-1
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3.5.0

      - name: Setup Rust
        if: inputs.build_rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build Rust FFI library
        if: inputs.build_rust
        run: |
          cd iceberg_rust_ffi
          cargo build --release

      - name: Set ICEBERG_RUST_LIB environment variable
        if: inputs.build_rust
        run: echo "ICEBERG_RUST_LIB=${{ github.workspace }}/iceberg_rust_ffi/target/release" >> $GITHUB_ENV

      - name: Initialize containers
        uses: gacts/run-and-post-run@v1
        with:
          run: |
            docker network create iceberg_net
            docker run -d --name minio \
              --network=iceberg_net -p 9000:9000 \
              -e MINIO_ROOT_USER=root \
              -e MINIO_ROOT_PASSWORD=password \
              -e MINIO_DOMAIN=minio \
              -v ${{ github.workspace }}/assets/tpch:/input \
              -v ${{ github.workspace }}/assets/incremental:/input_incremental \
              minio/minio:latest server /data/
            until (docker exec minio mc alias set minio http://localhost:9000 root password) do echo '... waiting ...' && sleep 1; done;
            docker exec minio mc mb minio/warehouse
            docker exec minio mc cp -r /input/tpch.sf01/ minio/warehouse/tpch.sf01/
            docker exec minio mc cp -r /input_incremental/ minio/warehouse/incremental/;
            docker run -d --name rest \
              --network=iceberg_net \
              -p 8181:8181 \
              -v ${{ github.workspace }}/assets/rest:/tmp \
              -e AWS_ACCESS_KEY_ID=root \
              -e AWS_SECRET_ACCESS_KEY=password \
              -e AWS_ENDPOINT_URL=http://minio:9000 \
              -e AWS_REGION=us-east-1 \
              -e CATALOG_S3_ENDPOINT=http://minio:9000 \
              -e CATALOG_WAREHOUSE=s3://warehouse \
              -e CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO apache/iceberg-rest-fixture
          post:
            docker stop rest minio && docker rm rest minio && docker network rm iceberg_net

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ inputs.julia_version }}
          arch: ${{ inputs.arch }}

      - uses: actions/cache@v4
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-

      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
        with:
          file: lcov.info
